CREATE DATABASE Karavan_4529
USE [Karavan_4529]
--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[KADMINISTRATOR] (
[Id_admin] [numeric](18, 0) IDENTITY NOT NULL,
[username] [nvarchar] (50) NULL,
[password] [nvarchar] (50) NULL,
[ime] [nvarchar] (50) NULL,
[telefon] [nvarchar] (50) NULL
CONSTRAINT [PK_KADMINISTRATOR] PRIMARY KEY CLUSTERED 
(
	[Id_admin] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
CREATE TABLE [dbo].[JAZIK] (
[id_jazik] [numeric](18, 0) IDENTITY NOT NULL,
[jazik] [nvarchar] (50) NULL
CONSTRAINT [PK_JAZIK] PRIMARY KEY CLUSTERED 
(
	[id_jazik] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[KNOVOST] (
[id_novost] [numeric](18, 0) IDENTITY NOT NULL,
[adm_id_admin] [numeric](18, 0) NULL,
[jazik_id_jazikn] [numeric](18, 0) NULL, 
[naslov] [nvarchar] (50) NULL,
[opis] [nvarchar] (1500) NULL,
[datum_od] [datetime] NULL,
[datum_do] [datetime] NULL 
CONSTRAINT [PK_KNOVOST] PRIMARY KEY CLUSTERED 
(
	[id_novost] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[KDOKUMENT] (
[id_dokument] [numeric](18, 0) IDENTITY NOT NULL,
[naslov] [nvarchar] (50) NULL,
[jazik_id_jazikd] [numeric](18, 0) NULL, 
[dokument] [nvarchar] (50) NULL,
[prikaz] [numeric](18, 0) NULL, 
CONSTRAINT [PK_kdokument] PRIMARY KEY CLUSTERED 
(
	[id_dokument] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[EMAIL] (
[id_posetitel] [numeric](18, 0) IDENTITY NOT NULL,
[ime] [nvarchar] (50) NULL,
[mail] [nvarchar] (50) NULL, 
CONSTRAINT [PK_EMAIL] PRIMARY KEY CLUSTERED 
(
	[id_posetitel] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[EMAIL_GRUPA] (
[ID_GRUPA] [numeric](18, 0) IDENTITY NOT NULL, 
[JAZIK_ID_JAZIKM] [numeric](18, 0) NULL, 
[NAZIV] [nvarchar] (50) NULL,
[aktivna] [numeric](18, 0) NULL 
CONSTRAINT [PK_EMAIL_GRUPA] PRIMARY KEY CLUSTERED 
(
	[ID_GRUPA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[EMAIL_PORAKA] (
[ID_PORAKA] [numeric](18, 0) IDENTITY NOT NULL,
[GRUPA_ID_GRUPA] [numeric](18, 0) NULL,
[DATUM] [datetime] NULL,
[NASLOV] [nvarchar] (50) NULL,
[TEKST] [nvarchar] (500) NULL 
CONSTRAINT [PK_EMAIL_PORAKA] PRIMARY KEY CLUSTERED 
(
	[ID_PORAKA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[MAILING] (
[EMAIL_ID_POSETITEL] [numeric](18, 0) NULL,
[EMAIL_ID_GRUPA] [numeric](18, 0) NULL
)

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[GALERIJA] (
[Id_galerija] [numeric](18, 0) IDENTITY NOT NULL,
[preview] [numeric](18, 0) NULL
CONSTRAINT [PK_GALERIJA] PRIMARY KEY CLUSTERED 
(
	[Id_galerija] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[GALERIJA_OPIS] (
[gal_id_galerija] [numeric](18, 0) NULL,
[jazik_id_jazikg] [numeric](18, 0) NULL,
[naslov] [nvarchar] (50) NULL,
[opis] [nvarchar] (500) NULL
)

--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

CREATE TABLE [dbo].[GALERIJA_SLIKA] (
[id_slika] [numeric](18, 0) IDENTITY NOT NULL,
[gal_id_galerijas] [numeric](18, 0) NULL,
[opisslika] [nvarchar] (300) NULL,
[slika] [nvarchar] (50) NULL,
[OPISSLIKAENG] [nvarchar] (300) NULL, 
CONSTRAINT [PK_GALERIJA_SLIKA] PRIMARY KEY CLUSTERED 
(
	[id_slika] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
--AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
